### ISSUE TITLE
Compile on Go < 1.13 failing

### ISSUE THREAD

**Issue by thaJeztah** [moby/sys#12]
Noticed this in one of our Jenkins jobs when compiling runc from commit https://github.com/opencontainers/runc/commit/9ec5b03e5af6e5f9fad4008df1d23f80141d38a9

```

 ---> Running in 4abcf2a2aa1c
warning: empty strings as pathspecs will be made invalid in upcoming releases. please use . instead if you meant to match all paths
CGO_ENABLED=1 go build  -tags "seccomp apparmor netgo osusergo" -installsuffix netgo -ldflags "-w -extldflags -static -X main.gitCommit="9ec5b03e5af6e5f9fad4008df1d23f80141d38a9" -X main.version=1.0.0-rc10+dev " -o runc .
# github.com/opencontainers/runc/vendor/github.com/moby/sys/mountinfo
vendor/github.com/moby/sys/mountinfo/mountinfo.go:8:9: undefined: parseMountTable
vendor/github.com/moby/sys/mountinfo/mountinfo.go:16:9: undefined: parseInfoFile
Makefile:44: recipe for target 'static' failed
make: *** [static] Error 2
The command '/bin/sh -c . /binaries-commits &&     git checkout -q "$RUNC_COMMIT" &&     make BUILDTAGS='seccomp apparmor' static && make install' returned a non-zero code: 2
Makefile:61: recipe for target 'image-linux' failed
make: *** [image-linux] Error 2
make: Leaving directory '/home/ubuntu/workspace/release-packaging_PR-508/docker-ce/components/packaging/image'
script returned exit code 2
```

**Comment by thaJeztah** [comment]
@kolyshkin PTAL (haven't dug into this one yet)

**Comment by thaJeztah** [comment]
Ah, looks like it's probably building on Go 1.12, but not sure why it's picking a recent version of runc on that branch; investigating

**Comment by thaJeztah** [comment]
Closing this, because this looks to be expected
